# Generated by Django 5.2.12 on 2026-04-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_panorama_configpump_plugin",
            "0003_alter_connectiontemplate_file_name_prefix",
        ),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
        migrations.AddField(
            model_name="connectiontemplate",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.owner",
            ),
        ),
    ]
