# Generated by Django 6.1 on 2026-09-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_panorama_configpump_plugin",
            "0004_connection_owner_connectiontemplate_owner",
        ),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="connectiontemplate",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
    ]
